#include "../libft/libft.h"
#include "../ft_printf.h"

int main(void)
{
ft_printf("%c\n", '0');
printf("%c\n", '0');
ft_printf(" %c \n", '0');
printf(" %c \n", '0');
ft_printf("10%c\n", '0');
printf("10%c\n", '0');
ft_printf("%10c\n", '0');
printf("%10c\n", '0');
ft_printf("-10%c\n", '0');
printf("-10%c\n", '0');
ft_printf("%-10c\n", '0');
printf("%-10c\n", '0');
ft_printf("%-10c\n", '0');
ft_printf("%*c\n", 1, '0');
printf("%*c\n", 1, '0');
ft_printf("%*c\n", 0, '0');
printf("%*c\n", 0, '0');
ft_printf("%*c\n", 2, '0');
printf("%*c\n", 2, '0');
ft_printf("%*c\n", 0, '0');
printf("%*c\n", 0, '0');
ft_printf("%*c\n", 10, '0');
printf("%*c\n", 10, '0');
ft_printf("%*c\n", -10, '0');
printf("%*c\n", -10, '0');
ft_printf("%*c%*c\n", -10, '0', 10, '1');
printf("%*c%*c\n", -10, '0', 10, '1');
ft_printf("*%c%*c\n", '0', 10, '1');
printf("*%c%*c\n", '0', 10, '1');
ft_printf("%*c%c*\n", -10, '0', '1');
printf("%*c%c*\n", -10, '0', '1');
ft_printf("%-10c*\n",'0');
printf("%-10c*\n",'0');
ft_printf("%-10c%*c%c*\n",'0', 10, '1', '2');
printf("%-10c%*c%c*\n",'0', 10, '1', '2');
ft_printf("%c%c%c*\n",'0', '1', '2');
printf("%c%c%c*\n",'0', '1', '2');
ft_printf("%-c%-c%c*\n", 1, '0', 0);
printf("%-c%-c%c*\n", 1, '0', 0);
ft_printf("%c\n", '0' - 256);
printf("%c\n", '0' - 256);
ft_printf("%c\n", '0' + 256);
printf("%c\n", '0' + 256);
ft_printf("%c\n", 0);
printf("%c\n", 0);
ft_printf("0%c\n", 0);
printf("0%c\n", 0);
ft_printf("%c\n", -129);
printf("%c\n", -129);
//ft_printf("%c\n", 128);
//printf("%c\n", 128);
ft_printf("%-*c\n", 10, '1');
printf("%-*c\n", 10, '1');
ft_printf(" -%*c* -%-*c* \n", -2, 0, 2, 0);
printf(" -%*c* -%-*c* \n", -2, 0, 2, 0);
ft_printf(" -%-*c* -%-*c* \n", 2, 0, -2, 0);
printf(" -%-*c* -%-*c* \n", 2, 0, -2, 0);
ft_printf(" -%*c* -%-*c* \n", -1, 0, 1, 0);
printf(" -%*c* -%-*c* \n", -1, 0, 1, 0);
ft_printf(" -%-*c* -%-*c* \n", 2, 0, -2, 0);
printf(" -%-*c* -%-*c* \n", 2, 0, -2, 0);
ft_printf(" -%-2c* -%2c* \n", 0, 0);
printf(" -%-2c* -%2c* \n", 0, 0);
sleep(9);
}